steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-southeast2-docker.pkg.dev/wijiwaste/backend-ml/wijiwaste-mlapi', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-southeast2-docker.pkg.dev/wijiwaste/backend-ml/wijiwaste-mlapi']

- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'deploy', 'my-cloud-run-service',
    '--image', 'asia-southeast2-docker.pkg.dev/wijiwaste/backend-ml/wijiwaste-mlapi',
    '--region', 'us-central1',
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--update-secrets', 'GOOGLE_APPLICATION_CREDENTIALS=credentials:latest'
  ]


options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s